-- MySQL Script generated by MySQL Workbench
-- Mon Jan 11 08:29:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema electronPV
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electronPV
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electronPV` DEFAULT CHARACTER SET utf8 ;
USE `electronPV` ;

-- -----------------------------------------------------
-- Table `electronPV`.`negocio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`negocio` (
  `rut` INT NOT NULL,
  `razon_social` VARCHAR(45) NOT NULL,
  `representante_legal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronPV`.`boleta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`boleta` (
  `numero_folio` INT NOT NULL,
  `negocio_rut` INT NOT NULL,
  PRIMARY KEY (`numero_folio`),
  INDEX `fk_boleta_negocio1_idx` (`negocio_rut` ASC) VISIBLE,
  CONSTRAINT `fk_boleta_negocio1`
    FOREIGN KEY (`negocio_rut`)
    REFERENCES `electronPV`.`negocio` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronPV`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`cliente` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `numero_telefono` INT NOT NULL,
  `cuenta` INT NOT NULL,
  `tipo_cuenta` VARCHAR(45) NOT NULL,
  `abonos` INT NULL,
  `nuevo_abono` INT NULL,
  `deuda` INT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronPV`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`venta` (
  `idventa` INT NOT NULL,
  `producto_codigo_barras` VARCHAR(50) NOT NULL,
  `boleta_numero_folio` INT NOT NULL,
  `cliente_rut` INT NOT NULL,
  `hora_venta` DATETIME NOT NULL,
  `medio_de_pago` VARCHAR(45) NOT NULL,
  `venta_total` VARCHAR(45) NOT NULL,
  `firma_sii` VARCHAR(45) NOT NULL,
  `venta_neta` INT NOT NULL,
  `cantidad_productos` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_producto_idx` (`producto_codigo_barras` ASC) VISIBLE,
  INDEX `fk_venta_boleta1_idx` (`boleta_numero_folio` ASC) VISIBLE,
  INDEX `fk_venta_cliente1_idx` (`cliente_rut` ASC) VISIBLE,
  CONSTRAINT `fk_venta_producto`
    FOREIGN KEY (`producto_codigo_barras`)
    REFERENCES `electronPV`.`producto` (`codigo_barras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_boleta1`
    FOREIGN KEY (`boleta_numero_folio`)
    REFERENCES `electronPV`.`boleta` (`numero_folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`cliente_rut`)
    REFERENCES `electronPV`.`cliente` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronPV`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`producto` (
  `codigo_barras` VARCHAR(50) NOT NULL,
  `venta_idventa` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `granel` VARCHAR(2) NOT NULL,
  `productocol` VARCHAR(45) NULL,
  `precio` INT NULL,
  `precio_kilo` INT NULL,
  `precio_neto` INT NULL,
  `stock` INT NOT NULL,
  `ventas_totales` INT NOT NULL,
  PRIMARY KEY (`codigo_barras`),
  INDEX `fk_producto_venta1_idx` (`venta_idventa` ASC) VISIBLE,
  CONSTRAINT `fk_producto_venta1`
    FOREIGN KEY (`venta_idventa`)
    REFERENCES `electronPV`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electronPV`.`cierre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electronPV`.`cierre` (
  `dia_cierre` DATETIME NOT NULL,
  `venta_diaria` INT NOT NULL,
  `total_venta` INT NOT NULL,
  `cantidad_debito` INT NOT NULL,
  `cantidad_credito` INT NOT NULL,
  `cantidad_efectivo` INT NOT NULL,
  `producto_mas_vendido` INT NULL,
  PRIMARY KEY (`dia_cierre`),
  UNIQUE INDEX `dia_cierre_UNIQUE` (`dia_cierre` ASC) VISIBLE,
  INDEX `fk_cierre_venta1_idx` (`venta_diaria` ASC) VISIBLE,
  CONSTRAINT `fk_cierre_venta1`
    FOREIGN KEY (`venta_diaria`)
    REFERENCES `electronPV`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
